name: SSH Connect

on:
  workflow_dispatch:
  schedule:
    - cron: '6 8 * */2 *'  #Runs at 08:06, every 2 months

jobs:
  connect:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko
          pip install requests

      - name: Run SSH connection script
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS_JSON }}
        run: python ssh.py
